#!/bin/bash
 
NAME="project"                               # Name of the application
DJANGODIR=$PWD                               # Django project directory
BIND=0.0.0.0:8000                            # we will communicte using this unix socket
USER=$USER                                   # the user to run as
GROUP=$USER                                  # the group to run as
NUM_WORKERS=1                                # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=project.settings      # which settings file should Django use
DJANGO_WSGI_MODULE=project.wsgi              # WSGI module name
 
echo "Starting $NAME as `whoami`"
 
# Activate the virtual environment
cd $DJANGODIR
# source .env/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
 
# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
 
# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug \
  --bind=$BIND
