FROM ubuntu
RUN apt-get update
RUN apt-get install python2.7 make python-pip libssl-dev -y

RUN alias python=python2.7
WORKDIR /project
ADD ../ /project
RUN make dev-setup

EXPOSE 80

CMD ./gunicorn_start
